#   ===========     Common and SSL   ===========
server:
  port: 8443
  ssl:
    key-store: target/keystore.jks
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: marks-table


#   ===========     Spring and Database (postgres + hibernate)    ===========
spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/students_marks_first
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true